imagetag: 1.0
imagename: CONTAINER_REGISTRY_IMAGE_NAME_HERE
serviceNameFront: meli-api-service
environmentName: dev
serviceType: LoadBalancer
containerPort: 5000
requestsCpu: 250m
requestsMemory: 500Mi
limitsCpu: 500m
limitsMemory: 1000Mi
minReadySeconds: 60
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
