apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceNameFront }}
  labels:
    name: {{ .Values.serviceNameFront }}
  annotations:
    networking.gke.io/load-balancer-type: Internal
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 5000
    targetPort: {{ .Values.containerPort }} 
  selector:
    app: {{ .Values.serviceNameFront }}
